# Workflow pro Build a Deploy Node.js aplikace na Azure Functions
name: Build and deploy Node.js project to Azure Function App - edu-chat-functions-node

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # cesta k tvé aplikaci
  NODE_VERSION: '20' # verze Node.js, kterou používáš

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm install --production

      # Optional: Spuštění testů
      - name: Run tests (if any)
        run: npm test || echo "No tests found, skipping..."

      - name: Zip artifact for deployment
        run: |
          zip -r release.zip . -x "node_modules/*" # Nezahrnovat node_modules

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write # Nutné pro přihlášení k Azure

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_32744267A37F40C08B797ECBD439EC6F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_58B4A9E33DCC4B76883D691C9F265EA3 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_150B21BC872447409D28A3CE331FE723 }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: 'edu-chat-functions-node'
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
